---
- hosts: loadbalancer
  gather_facts: true

  tasks:
    - name: install haproxy
      dnf: name=haproxy state=latest
      sudo: yes

    - name: add haproxy config
      template: src=templates/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg backup=yes
      notify: restart haproxy
      sudo: yes

    - name: haproxy allow any connection selinux
      raw: sudo setsebool -P haproxy_connect_any 1

    - command: /bin/true
      notify: flush iptables

    - name: ensure haproxy is started
      service: name=haproxy state=started
      sudo: yes

  handlers:
    - name: restart haproxy
      service: name=haproxy state=restarted
      sudo: yes

    - name: flush iptables
      shell: iptables -F
      sudo: yes
